const RolesNames = {
	ADMINISTRADOR: 'ADMINISTRADOR',
	ALMACEN_ENCARGADO: 'ALMACEN_ENCARGADO',
	ALMACEN_AUXILIAR: 'ALMACEN_AUXILIAR',
	PRESUPUESTO: 'PRESUPUESTO',
	COMPRAS: 'COMPRAS',
	CENTROCOSTOS_ENCARGADO: 'CENTROCOSTOS_ENCARGADO',
	CENTROCOSTOS_AUXILIAR: 'CENTROCOSTOS_AUXILIAR'
}

export default RolesNames
